---

- name: "RHEL-08-040171 | HIGH | PATCH | The x86 Ctrl-Alt-Delete key sequence in RHEL 8 must be disabled if a graphical user interface is installed."
  block:
      - name: "RHEL-08-040171 | HIGH | PATCH | The x86 Ctrl-Alt-Delete key sequence in RHEL 8 must be disabled if a graphical user interface is installed. | Check for setting existing"
        command: grep -s logout /etc/dconf/db/local.d/*
        changed_when: false
        failed_when: false
        register: rhel_08_040171_logout_settings_status

      - name: "RHEL-08-040171 | HIGH | PATCH | The x86 Ctrl-Alt-Delete key sequence in RHEL 8 must be disabled if a graphical user interface is installed. | Add if missing"
        lineinfile:
            path: /etc/dconf/db/local.d/00-disable-CAD
            regexp: "{{ item.regexp }}"
            line: "{{ item.line }}"
            insertafter: "{{ item.insertafter }}"
            create: yes
            owner: root
            group: root
            mode: 0644
        with_items:
            - { regexp: '^\[org/gnome/settings-daemon/plugins/media-keys\]', line: '[org/gnome/settings-daemon/plugins/media-keys]', insertafter: 'EOF' }
            - { regexp: 'logout=', line: "logout=''", insertafter: '\[org/gnome/settings-daemon/plugins/media-keys\]' }
        when: rhel_08_040171_logout_settings_status.stdout | length == 0

      - name: "RHEL-08-040171 | HIGH | PATCH | The x86 Ctrl-Alt-Delete key sequence in RHEL 8 must be disabled if a graphical user interface is installed. | Edit if exists"
        replace:
            path: "{{ rhel_08_040171_logout_settings_status.stdout }}"
            regexp: '^[L|l]ogout=.*'
            replace: "logout=''"
        when: rhel_08_040171_logout_settings_status.stdout | length > 0
  when:
      - rhel_08_040171
      - "'gnome-desktop' in ansible_facts.packages"
  tags:
      - RHEL-08-040171
      - CAT1
      - CCI-000366
      - SRG-OS-000480-GPOS-00227
      - SV-230530r646883_rule
      - V-230530
      
