---

- name: "RHEL-08-010820 | HIGH | PATCH | Unattended or automatic logon via the RHEL 8 graphical user interface must not be allowed."
  lineinfile:
      path: /etc/gdm/custom.conf
      regexp: (?i)automaticloginenable
      line: AutomaticLoginEnable=false
      insertafter: '\[daemon\]'
  when:
      - rhel8stig_gui
      - rhel_08_010820
  tags:
      - RHEL-08-010820
