---

- name: |
        "RHEL-08-010140 | HIGH | PATCH | RHEL 8 operating systems booted with United Extensible Firmware Interface (UEFI) implemented must require authentication upon booting into single-user mode and maintenance."
        "RHEL-08-010150 | HIGH |PATCH | RHEL 8 operating systems booted with a BIOS must require authentication upon booting into single-user and maintenance modes."
  block:
      - name: |
            "RHEL-08-010140 | HIGH | PATCH | RHEL 8 operating systems booted with United Extensible Firmware Interface (UEFI) implemented must require authentication upon booting into single-user mode and maintenance. | Set Grub Password"
            "RHEL-08-010150 | HIGH | PATCH | RHEL 8 operating systems booted with a BIOS must require authentication upon booting into single-user and maintenance modes. | Set Grub Password"
        lineinfile:
            path: "{{ rhel8stig_grub_cfg_path | dirname }}/user.cfg"
            create: yes
            regexp: ^GRUB2_PASSWORD=
            line: "GRUB2_PASSWORD={{ rhel8stig_bootloader_password_hash }}"
            owner: root
            group: root
            mode: 0640
        notify: confirm grub2 user cfg

      - name: |
            "RHEL-08-010140 | HIGH | PATCH | RHEL 8 operating systems booted with United Extensible Firmware Interface (UEFI) implemented must require authentication upon booting into single-user mode and maintenance. | Set UEFI superusers"
            "RHEL-08-010150 | HIGH | PATCH | RHEL 8 operating systems booted with a BIOS must require authentication upon booting into single-user and maintenance modes. | Set UEFI superusers"
        lineinfile:
            dest: "{{ rhel8stig_grub_cfg_path | dirname }}/grub.cfg"
            regexp: '^set superusers'
            line: 'set superusers="{{ rhel8stig_boot_superuser }}"'
            insertafter: '### BEGIN /etc/grub.d/01_users ###'
        notify: confirm grub2 user cfg
  when:
      - not system_is_ec2
      - rhel_08_010140 or
        rhel_08_010150
  tags:
      - RHEL-08-010140
      - RHEL-08-010150
      - CAT1
      - CCI-000213
      - SRG-OS-000080-GPOS-00048
      - SV-230234r627750_rule
      - SV-230235r627750_rule
      - V-230234
      - V-230235
      - grub
      - bootloader
