---

- name: "RHEL-08-010020 | HIGH | PATCH | The Red Hat Enterprise Linux operating system must implement NIST FIPS-validated cryptography for the following: to provision digital signatures, to generate cryptographic hashes, and to protect data requiring data-at-rest protections in accordance with applicable federal laws, Executive Orders, directives, policies, regulations, and standards."
  block:
      - name: "RHEL-08-010020 | HIGH | PATCH | The Red Hat Enterprise Linux operating system must implement NIST FIPS-validated cryptography for the following: to provision digital signatures, to generate cryptographic hashes, and to protect data requiring data-at-rest protections in accordance with applicable federal laws, Executive Orders, directives, policies, regulations, and standards."
        dnf:
            name: dracut-fips
            state: present
        notify: rebuild initramfs

      - name: "RHEL-08-010020 | HIGH | PATCH | The Red Hat Enterprise Linux operating system must implement NIST FIPS-validated cryptography for the following: to provision digital signatures, to generate cryptographic hashes, and to protect data requiring data-at-rest protections in accordance with applicable federal laws, Executive Orders, directives, policies, regulations, and standards. | Enables FIPS mode on kernel"
        command: fips-mode-setup --enable
        register: rhel_08_010020_kernel_fips_enable
        changed_when: rhel_08_010020_kernel_fips_enable.rc == 0

      - name: "RHEL-08-010020 | HIGH | AUDIT | Check if prelink package is installed"
        command: rpm -q prelink
        args:
            warn: no
        changed_when: no
        failed_when: no
        check_mode: no
        register: rhel_08_010020_prelink_installed

      - name: "RHEL-08-010020 | HIGH | PATCH | Disable prelinking."
        lineinfile:
            dest: /etc/sysconfig/prelink
            regexp: ^#?PRELINKING
            line: PRELINKING=no
        when: rhel_08_010020_prelink_installed.rc == 0
        notify: undo existing prelinking

      - name: "RHEL-08-010020 | HIGH | AUDIT | Check for GRUB_CMDLINE_LINUX in /etc/default/grub"
        command: grep -P '^\s*GRUB_CMDLINE_LINUX=".*"$' /etc/default/grub
        check_mode: no
        failed_when: no
        changed_when: rhel_08_010020_default_grub_missing_audit.rc > 0
        register: rhel_08_010020_default_grub_missing_audit

      - name: "RHEL-08-010020 | HIGH | AUDIT | parse sane GRUB_CMDLINE_LINUX from /proc/cmdline"
        command: grep -oP ' ro \K.*?(?= ?LANG=)' /proc/cmdline
        check_mode: no
        changed_when: no
        failed_when: rhel_08_010020_grub_cmdline_linux_audit.rc > 1
        when: rhel_08_010020_default_grub_missing_audit is changed
        register: rhel_08_010020_grub_cmdline_linux_audit

      - name: "RHEL-08-010020 | HIGH | PATCH | Copy over a sane /etc/default/grub"
        template:
            src: etc_default_grub.j2
            dest: /etc/default/grub
            owner: root
            group: root
            mode: 0644
        vars:
            grub_cmdline_linux: "{{ rhel_08_010020_grub_cmdline_linux_audit.stdout }}"
        when: rhel_08_010020_default_grub_missing_audit is changed

      - name: "RHEL-08-010020 | HIGH | PATCH | fips=1 must be in /etc/default/grub"
        replace:
            path: /etc/default/grub
            regexp: "{{ rhel8stig_regexp_quoted_params }}"
            replace: "{{ rhel8stig_replace_quoted_params }}"
        vars:
            key: GRUB_CMDLINE_LINUX
            param: fips
            value: 1
            append: yes  # this is the default
        when:
            - not ansible_check_mode or
              rhel_08_010020_default_grub_missing_audit is not changed
        notify:
            - confirm grub2 user cfg

      - name: "RHEL-08-010020 | HIGH | PATCH | If /boot or /boot/efi reside on separate partitions, the kernel parameter boot=<partition> must be added to the kernel command line."
        replace:
            path: /etc/default/grub
            regexp: "{{ rhel8stig_regexp_quoted_params }}"
            replace: "{{ rhel8stig_replace_quoted_params }}"
        with_items:
            - "{{ ansible_mounts | json_query(query) }}"
        vars:
            query: "[?mount=='{{ rhel8stig_boot_part }}'] | [0]"
            key: GRUB_CMDLINE_LINUX
            param: boot
            value: UUID={{ item.uuid }}
            insert: yes
        when:
            - rhel8stig_boot_part not in ['/', '']
            - not ansible_check_mode or
              rhel_08_010020_default_grub_missing_audit is not changed
        notify: confirm grub2 user cfg
        register: result

      - name: "RHEL-08-010020 | HIGH | AUDIT | Verify kernel parameters in /etc/default/grub"
        command: grep -P '^\s*GRUB_CMDLINE_LINUX=".*(?<=[" ]){{ item | regex_escape }}(?=[" ]).*"$' /etc/default/grub
        check_mode: no
        with_items:
            - fips=1
            - boot=UUID={{ ansible_mounts | json_query(query) }}
        vars:
            query: "[?mount=='{{ rhel8stig_boot_part }}'].uuid | [0]"
        register: rhel_08_010020_audit
        when:
            - not ansible_check_mode or
              rhel_08_010020_default_grub_missing_audit is not changed
            - rhel8stig_boot_part not in ['/', ''] or
              'boot=' not in item
        changed_when:
            - ansible_check_mode
            - rhel_08_010020_audit is failed
        failed_when:
            - rhel_08_010020_audit is failed
            - not ansible_check_mode or
              rhel_08_010020_audit.rc > 1
  when: rhel_08_010020
  tags:
      - RHEL-08-010020
      - CAT1
      - CCI-000068
      - SRG-OS-000033-GPOS-00014
      - SV-230223r627750_rule
      - V-230223
