---

- name: "RHEL-08-010820 | HIGH | PATCH | Unattended or automatic logon via the RHEL 8 graphical user interface must not be allowed."
  lineinfile:
      path: /etc/gdm/custom.conf
      regexp: (?i)automaticloginenable
      line: AutomaticLoginEnable=false
      insertafter: '\[daemon\]'
  when:
      - rhel8stig_gui
      - rhel_08_010820
  tags:
      - RHEL-08-010820
      - CAT1
      - CCI-000366
      - SRG-OS-000480-GPOS-00229
      - SV-230329r627750_rule
      - V-230329
