---

- name: "RHEL-08-010000 | HIGH | AUDIT | The RHEL 8 must be a vendor-supported release."
  debug:
      msg: Minimum supported version of {{ ansible_distribution }} is {{ rhel8stig_min_supported_os_ver[ansible_distribution] }}
  changed_when: ansible_distribution_version is not version_compare(rhel8stig_min_supported_os_ver[ansible_distribution], '>=')
  when:
      - rhel_08_010000
  tags:
      - RHEL-08-010000
      - CAT1
      - CCI-000366
      - SRG-OS-000480-GPOS-00227
      - SV-230221r627750_rule
      - V-230221


